### ISSUE TITLE
Feature request: add KVM support

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [ThunderStorms21th/Galaxy-S10#2]
I want to use KVM with this kernel

https://github.com/limboemu/limbo/wiki/KVM

**Comment by ThunderStorms21th** [comment]
Yes, I want to upstream to Linux 4.14.214 but above 166 I have the problem with Little cores - all the time are at max freq - 1950MHz. Im trying to fix this...
KVM it is too in later updates probably from 168...

**Comment by ThunderStorms21th** [comment]
oki, now fixed max freq at Little CPU, Im now on 172.

**Comment by ThunderStorms21th** [comment]
OK, I've added KVM - Virtual Machine and source is upstreamed to Linux 4.14.212.
Soon - update offcial.

**Comment by ThunderStorms21th** [comment]
If You want - PM me on telegram group - I will add You into the testers group...

**Comment by ericek111** [comment]
This is what I came here for. Is KVM usable with this kernel on Exynos, please?

**Comment by ThunderStorms21th** [comment]
> This is what I came here for. Is KVM usable with this kernel on Exynos, please?

someone said so doesnt work... but Ive added all stuff - ... :(

**Comment by ericek111** [comment]
So you think it should work? I haven't tripped Knox yet, so if someone with Exynos could test KVM with this kernel, that would be awesome.

**Comment by ThunderStorms21th** [comment]
I think it doesnt work bcose one user checked and for him doesnt work...sorry

**Comment by Prox-y** [comment]
i might be late but i wanted to ask, does this KVM support apply only for ARM architectures or does it work on limboo with x86_64 arches as well?

**Comment by ThunderStorms21th** [comment]
HI, I dont know ... I dont use it on Android and Im not insterested this feature.
