### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by incapdns** [ThunderStorms21th/Galaxy-S10#8]
Plz verify the path in **build** file

toolchain/clang-11/host/linux-x86/clang-r399163b/bin/clang

Error: PATH NOT FOUND

**Comment by ThunderStorms21th** [comment]
I use clang 8.0.8 and in toolchain folder ckang 11 is absent. Copy clang 11 into toolchain dir and change in ts-build.sh for clang 11. I dont verify bcose i dont use it.
